### ISSUE TITLE
Manipulação Incorreta de Datas nas Transações

### ISSUE THREAD

**Issue by Angthebender** [PedroCavalheiro/processos-g77#2]
### Relato de Problema 2

**Descrição**
Ao realizar transferências internas, o sistema regista a data da transação com base na data de execução, em vez da data inserida, causando discrepâncias e confusão.

**Passos para Reproduzir**

- Realize uma transferência interna e insira uma data específica para a transação.
- Complete a transação.
- Verifique a data registada.
- Veja o erro.

**Resultado Esperado**
A data registada deve coincidir com a data inserida durante a transação.

**Resultado Obtido**
A data registada é a data de execução, não a data inserida.

**Ambiente**
- **Tipo de Aplicação**: Progresso (Web)
- **Método de Autenticação**: Email e Senha
- **Sistema Operativo**: Vários (Windows 10, macOS Big Sur, etc.)
- **Versão do Browser**: Vários (Chrome 91, Firefox 89, etc.)
- **Data da ocorrência**: Contínua
- **Dispositivo**: Não aplicável

**Checklist**

- [x] Confirmo que estava a usar a versão mais recente da aplicação
- [x] Confirmo que não incluí dados pessoais ou credenciais no presente relatório

**Comment by PedroCavalheiro** [comment]
Insira capturas de ecrã, por favor.
