### ISSUE TITLE
Problema de Gestão de Permissões da Câmara

### ISSUE THREAD

**Issue by Angthebender** [PedroCavalheiro/processos-g77#5]
### Relato de Problema 5

**Descrição**
A aplicação espera indefinidamente pela permissão da câmara, que é utilizada para digitalizar códigos QR. Deveria haver um método alternativo para inserir o código manualmente caso a câmara não seja permitida.

**Passos para Reproduzir**

- Negue a permissão da câmara quando solicitado pela aplicação.
- Observe a resposta da aplicação.
- Tente encontrar uma alternativa para inserir o código.
- Veja o erro.

**Resultado Esperado**
A aplicação deve fornecer uma opção para inserir o código QR manualmente se a câmara não for permitida.

**Resultado Obtido**
A aplicação continua à espera da permissão da câmara sem fornecer uma alternativa.

**Ambiente**
- **Tipo de Aplicação**: Progresso (Web)
- **Método de Autenticação**: QR Code
- **Sistema Operativo**: Vários (Windows 10, macOS Big Sur, etc.)
- **Versão do Browser**: Vários (Chrome 91, Firefox 89, etc.)
- **Data da ocorrência**: Contínua
- **Dispositivo**: Não aplicável

**Checklist**

- [x] Confirmo que estava a usar a versão mais recente da aplicação
- [x] Confirmo que não incluí dados pessoais ou credenciais no presente relatório

**Comment by PedroCavalheiro** [comment]
É possível inserir um código mais abaixo, mas de facto deveria existir uma mensagem caso a permissão de câmera seja recusada.

**Comment by Angthebender** [comment]
A introdução da parte do código funciona bem, mas a parte da câmara não mostra qualquer notificação ou qualquer coisa que informe o utilizador sobre a permissão da câmara ser negada
![image](https://github.com/user-attachments/assets/079ba366-4b34-4d25-a47a-204b19e09026)
