### ISSUE TITLE
Página de Perfil Permite Entradas de Dados Inválidos

### ISSUE THREAD

**Issue by Angthebender** [PedroCavalheiro/processos-g77#6]
### Relato de Problema 6

**Descrição**
A página de perfil permite aos utilizadores inserir dados inválidos, como datas futuras para a data de nascimento e números excessivamente longos para campos como "Número de Contribuinte" e "Número de Utente SNS".

**Passos para Reproduzir**

- Aceda à página de perfil.
- Insira uma data futura para a data de nascimento.
- Insira mais de 9 dígitos para "Número de Contribuinte" e "Número de Utente SNS".
- Veja o erro.

**Resultado Esperado**
O sistema deve validar os dados e impedir entradas inválidas.

**Resultado Obtido**
Dados inválidos são aceites sem validação.

**Ambiente**
- **Tipo de Aplicação**: Progresso (Web)
- **Método de Autenticação**: Email e Senha
- **Sistema Operativo**: Vários (Windows 10, macOS Big Sur, etc.)
- **Versão do Browser**: Vários (Chrome 91, Firefox 89, etc.)
- **Data da ocorrência**: Contínua
- **Dispositivo**: Não aplicável

**Checklist**

- [x] Confirmo que estava a usar a versão mais recente da aplicação
- [x] Confirmo que não incluí dados pessoais ou credenciais no presente relatório

**Comment by PedroCavalheiro** [comment]
A aplicação está a agir como planeado para os campos de números de SNS, num. utente, etc. por poderem ser usados para outros subsistemas, pelo que não serão alterados. No caso da data de nascimento, deverá ser adicionada esta validação, tal como já está na data de expiração do documento de identificação.
